---
title: "Proyecto"
author: "Carlos Brenes"
date: "2024-10-15"
output:
  pdf_document: default
  html_document: default
---

```{r}
# Instalación de paquetes
install.packages("modeest")
install.packages("tidyverse")
install.packages("knitr")
install.packages("mlr")
install.packages("openxlsx")
install.packages("mvnormalTest")
install.packages("sjPlot")
install.packages("lavaan")
install.packages("semTools")
install.packages("semPlot")
install.packages("tidySEM")
install.packages("ggpubr")
install.packages("DescTools")
install.packages("FactoMineR")
install.packages("factoextra")
install.packages("effsize")
install.packages("rstatix")
install.packages("coin")
install.packages("gplots")
install.packages("gmodels")
install.packages("pastecs")
install.packages("writexl")
install.packages("polycor")
install.packages("skimr")
install.packages("mvnormalTest")
install.packages("GPArotation")
install.packages("tidySEM")
install.packages("EFAtools")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Activación de paquetes
library(readxl)
library(tidyverse)
library(skimr)
library(mlr)
library(openxlsx)
library(psych)
library(scales)
library(mvnormalTest)
library(GPArotation)
library(sjPlot)
library(lavaan)
library(semTools)
library(semPlot)
library(tidySEM)
library(Hmisc)
library(nortest)
library(ggplot2)
library(ggpubr)
library(DescTools)
library(FactoMineR)
library(factoextra)
library(effsize)
library(rstatix)
library(coin)
library(gplots)
library(gmodels)
library(EFAtools)
```

```{r}
# Limpia de base
base <- read_excel("base.xlsx")

colnames(base)[4] <- 'genero'
colnames(base)[2] <- 'universidad'
colnames(base)[3] <- 'ingreso'
colnames(base)[5] <- 'zona'
colnames(base)[6] <- 'area'
colnames(base)[7] <- 'beca'
colnames(base)[8] <- 'AF1'
colnames(base)[9] <- 'AF2'
colnames(base)[10] <- 'AF3'
colnames(base)[11] <- 'AF4'
colnames(base)[12] <- 'AF5'
colnames(base)[13] <- 'AF6'
colnames(base)[14] <- 'AF7'
colnames(base)[15] <- 'AF8'
colnames(base)[16] <- 'S1'
colnames(base)[17] <- 'S2'
colnames(base)[18] <- 'S3'
colnames(base)[19] <- 'S4'
colnames(base)[20] <- 'AC1'
colnames(base)[21] <- 'AC2'
colnames(base)[22] <- 'AC3'
colnames(base)[23] <- 'AC4'
colnames(base)[24] <- 'F1'
colnames(base)[25] <- 'F2'
colnames(base)[26] <- 'F3'
colnames(base)[27] <- 'F4'

base$genero[base$genero == 'Femenino'] <- "F"
base$genero[base$genero == 'Masculino'] <- "M"

base$area[base$area == 'Ciencias básicas (Matemática, Química, Biología, Física, etc.)'] <- 'Ciencias básicas'
base$area[base$area == 'Ciencias sociales (Sociología, Psicología, Educación, Administración, etc.)'] <- 'Ciencias sociales'
base$area[base$area == 'Artes y humanidades (Arte Escénico, Música, Filosofía, Literatura, etc.)'] <- 'Artes y humanidades'
base$area[base$area == 'Ingeniería (Arquitectura, Informática, Ingeniería Civil, Ingeniería Ambiental, etc.)'] <- 'Ingeniería'

base$universidad[base$universidad == 'Universidad Nacional de Costa Rica'] <- 'UNA'
base$universidad[base$universidad == 'Instituto Tecnológico de Monterrey'] <- 'TEC'
base$universidad[base$universidad == 'Universidad San Francisco de Quito'] <- 'USFQ'
view(base)
```

```{r}
# Redefinición (requiere tidyverse)
base <- mutate_at(base,vars(8:27),as.numeric)
```

```{r}
# Filtro por universidad (requiere tidyverse)

cr<-base %>%
  filter(universidad=="UNA")

```

```{r}
# Dimensiones

afectiva <- cr$AF1 + cr$AF2 + cr$AF3 + cr$AF4 + cr$AF5 + cr$AF6 + cr$AF7 + cr$AF8
social <- cr$S1 + cr$S2 + cr$S3 + cr$S4
academica <- cr$AC1 + cr$AC2 + cr$AC3 + cr$AC4
fisica <- cr$F1 + cr$F2 + cr$F3 + cr$F4
sp <- afectiva + social + academica + fisica

AF <- cr[,c(8:15)]
S <- cr[,c(16:19)]
AC <- cr[,c(20:23)]
FI <- cr[,c(24:27)] 

afectiva <- rescale(afectiva, to = c(1,7))
social <- rescale(social, to = c(1,7))
academica <- rescale(academica, to = c(1,7))
fisica <- rescale(fisica, to = c(1,7))
sp <- rescale(sp, to = c(1,7))

cr$afectiva <- afectiva
cr$social <- social
cr$academica <- academica
cr$fisica <- fisica
cr$sp <- sp
```

```{r}
# Bases
view(cr)
```

```{r}
# Análisis descriptivo
summary(cr)

table(cr$genero)
table(cr$zona)
table(cr$area)
table(cr$ingreso)
table(cr$beca)
table(cr$universidad)
skim(cr$genero)
```

```{r}
# Agrupación SP por dimensión
spAF <- cr$AF1 + cr$AF2 + cr$AF3 + cr$AF4 + cr$AF5 + cr$AF6 + cr$AF7 + cr$AF8
spS <- cr$S1 + cr$S2 + cr$S3 + cr$S4
spAC <- cr$AC1 + cr$AC2 + cr$AC3 + cr$AC4
spF <- cr$F1 + cr$F2 + cr$F3 + cr$F4
```

```{r}
# Reescalamiento de los SP
spAF <- rescale(spAF, to = c(1,7))
spS <- rescale(spS, to = c(1,7))
spAC <- rescale(spAC, to = c(1,7))
spF <- rescale(spF, to = c(1,7))
```

```{r}
library(modeest)

# Resumen SP
summary(cr$sp)
sd(cr$sp)
mfv(cr$sp)

# Por dimensión
summary(spAF)
sd(spAF)
mfv(spAF)

summary(spS)
sd(spS)
mfv(spS)

summary(spAC)
sd(spAC)
mfv(spAC)

summary(spF)
sd(spF)
mfv(spF)
```


```{r echo=FALSE,include=FALSE}
# Omegas y Alfas

# General
omega(AF, nfactors=4)
omega(S, nfactors=4)
omega(AC, nfactors=4)
omega(FI, nfactors=4)
```

```{r}
# Confirmatorio (requiere lavaan, semTools, semPlot y Hmisc, tidySEM)

modelo1 <- '
  subd1 =~ AF1+AF2+AF4
  subd2 =~ AF3+AF5+AF6+AF7+AF8
  
  afectivaC =~ subd1 + subd2
  
  socialC =~ S1+S2+S3+S4
  academicaC =~ AC1+AC2+AC3+AC4
  fisicaC =~ F1+F2+F3+F4
  
  '

modelo2 <- '
  subd1 =~ AF1+AF2+AF4
  subd2 =~ AF3+AF5+AF6+AF7+AF8
  afectivaC =~ subd1 + subd2
  
  social1 =~ S1+S2
  social2 =~ S3+S4
  socialC =~ social1 + social2
  
  academicaC =~ AC1+AC2+AC3+AC4
  
  fisicaC =~ F1+F2+F3+F4
  
  '

cfa1 <- cfa(model=modelo1, data=cr, orthogonal = F, std.lv=T, std.ov=T,test = "Satorra.Bentler",estimator="WLSMV",ordered=T)

cfa2 <- cfa(model=modelo2, data=cr, orthogonal = F, std.lv=T, std.ov=T,test = "Satorra.Bentler",estimator="WLSMV",ordered=T)
```

```{r}
# Análisis de Confirmatorio

fitmeasures(cfa1, fit.measures="all")

fitmeasures(cfa2, fit.measures="all")

```

```{r}
# Gráfica de Confirmatorio

semPaths(cfa1, residuals = F,
         sizeMan = 7, "std",
         posCol = c("skyblue4","red"),
         edge.color = "skyblue4",
         edge.label.cex = 1.2,
         layout = "tree", style = "lisrel", rotation = 4
         )

semPaths(cfa2, residuals = F,
         sizeMan = 7, "std",
         posCol = c("skyblue4","red"),
         edge.color = "skyblue4",
         edge.label.cex = 1.2,
         layout = "tree", style = "lisrel", rotation = 4
         )
```

```{r}
# Pruebas de Normalidad (Anderson-Darling) (requiere nortest)

ad.test(afectiva)
ad.test(social)
ad.test(academica)
ad.test(fisica)
ad.test(sp)
```

```{r}
# OE2: Relación entre STEM y SP (requiere ggpubr)

# Filtro STEM y no STEM

base$STEM <- base$area

base$STEM[base$STEM %in% c("Ciencias básicas", "Ingeniería")] <- 'STEM'
base$STEM[base$STEM %in% c("Ciencias sociales", "Artes y humanidades", "Otras")] <- 'No STEM'

# Filtro STEM y no STEM CR 

cr$STEM <- cr$area

cr$STEM[cr$STEM %in% c("Ciencias básicas", "Ingeniería")] <- 'STEM'
cr$STEM[cr$STEM %in% c("Ciencias sociales", "Artes y humanidades", "Otras")] <- 'No STEM'

# Boxplot

ggboxplot(base, x = "STEM", y = "sp",
          color = "STEM", palette = c("#00AFBB","#E7B800"),
          order = c("STEM", "No STEM"),
          ylab = "Sentido de Pertenencia",
          xlab = "Tipo de carrera (STEM o No STEM)")

kruskal.test(sp~STEM, data = base)

pairwise.wilcox.test(base$sp, base$STEM, p.adjust.method = "BH")

#tamaño de efecto (requiere el paquete effectsize)

cliff.delta(base$sp, base$STEM, conf.level=.95, 
                         use.unbiased=TRUE, use.normal=FALSE, 
                         return.dm=FALSE,
                         formula = sp~STEM,
                         data = base)
```


```{r} 
# OE3: Relación entre universidad y SP (requiere ggpubr)

ggboxplot(base, x = "universidad", y = "sp",
          color = "universidad", palette = c("#00AFBB","#E7B800","#FC4E07"),
          order = c("UNA", "TEC", "USFQ"),
          ylab = "Sentido de Pertenencia",
          xlab = "Universidad")

kruskal.test(sp~universidad, data = base)

summary(mexico$sp)

pairwise.wilcox.test(base$sp, base$universidad, p.adjust.method = "BH")

rstatix::wilcox_effsize(
  data = base,
  formula = sp~universidad,
  comparisons = NULL,
  ref.group = NULL,
  paired = FALSE,
  alternative = "two.sided",
  mu = 0,
  ci = FALSE,
  conf.level = 0.95,
  ci.type = "perc",
  nboot = 1000)
```

```{r}
# H1: Nivel y SP

# Filtro

cr$nivel <- cr$ingreso

cr$nivel[cr$nivel == '2024'] <- 'Primer nivel'
cr$nivel[cr$nivel %in% c("2023", "2020 a 2022", "2019 o antes")] <- 'Niveles superiores'

# Boxplot

ggboxplot(cr, x = "nivel", y = "sp",
          color = "nivel", palette = c("#00AFBB","#E7B800"),
          order = c("Primer nivel", "Niveles superiores"),
          ylab = "Sentido de Pertenencia",
          xlab = "Nivel de carrera")

# Bases por nivel

nivel1 <- cr %>%
  filter(nivel == 'Primer nivel')

summary(nivel1$sp)

nivelsup <- cr %>%
  filter(nivel == 'Niveles superiores')

summary(nivelsup$sp)

# Prueba de hipótesis
# H0: El grado de sentido de pertenencia de los estudiantes de la UNA, TEC y USFQ de primer nivel es mayor o igual que el de los estudiantes de niveles superiores.

#H1: El grado de sentido de pertenencia de los estudiantes de la UNA, TEC y USFQ de primer nivel es significativamente menor que el de los estudiantes de niveles superiores.

wilcox.test(x = nivel1$sp,
            y = nivelsup$sp,
            mu = 0,
            paired = F,
            var.equal = F,
            conf.int = T,
            conf.level = 0.95,
            alternative = "less")

# Se rechaza H1 :(
```

```{r}
#H2: Zona

# Boxplot

ggboxplot(cr, x = "zona", y = "sp",
          color = "zona", palette = c("#00AFBB","#E7B800"),
          order = c("Urbana", "Rural"),
          ylab = "Sentido de Pertenencia",
          xlab = "Zona de residencia")

# Bases por zona

urbana <- cr %>%
  filter(zona == 'Urbana')

rural <- cr %>%
  filter(zona == 'Rural')

# Prueba de hipótesis
# H0: El grado de sentido de pertenencia de los estudiantes de la UNA, TEC y USFQ de zona rural es mayor o igual que el de los estudiantes de zona urbana.

#H1: El grado de sentido de pertenencia de los estudiantes de la UNA, TEC y USFQ de zona rural es significativamente menor que el de los estudiantes de zona urbana.

wilcox.test(x = rural$sp,
            y = urbana$sp,
            mu = 0,
            paired = F,
            var.equal = F,
            conf.int = T,
            conf.level = 0.95,
            alternative = "less")

# Se rechaza H1 :(
```

```{r}
#H3: Beca

# Boxplot

ggboxplot(cr, x = "beca", y = "sp",
          color = "beca", palette = c("#00AFBB","#E7B800"),
          order = c("Sí", "No"),
          ylab = "Sentido de Pertenencia",
          xlab = "Posesión de beca")

# Bases por beca

beca <- cr %>%
  filter(beca == 'Sí')

nobeca <- cr %>%
  filter(beca == 'No')

# Prueba de hipótesis

# H0: El grado de sentido de pertenencia de los estudiantes de la UNA, TEC y USFQ que poseen beca es menor o igual que el de los estudiantes que no poseen beca.

#H1: El grado de sentido de pertenencia de los estudiantes de la UNA, TEC y USFQ que poseen beca es significativamente mayor que el de los estudiantes que no poseen beca.

wilcox.test(x = beca$sp,
            y = nobeca$sp,
            mu = 0,
            paired = F,
            var.equal = F,
            conf.int = T,
            conf.level = 0.95,
            alternative = "great")

# No se rechaza H1 :)
```

```{r}
# Extra: Pandemia

# Columna pandemia

cr$pandemia <- cr$ingreso

cr$pandemia[cr$pandemia == '2020 a 2022'] <- 'Pandemia'
cr$pandemia[cr$pandemia %in% c("2023", "2024")] <- 'Post-pandemia'
cr$pandemia[cr$pandemia == '2019 o antes'] <- 'Pre-pandemia'

# Boxplot

ggboxplot(cr, x = "pandemia", y = "sp",
          color = "pandemia", palette = c("#00AFBB","#E7B800", "#FC4E07"),
          order = c("Pre-pandemia", "Pandemia", "Post-pandemia"),
          ylab = "Sentido de Pertenencia",
          xlab = "Ingreso durante pandemia")

# Bases por pandemia

pre <- cr %>%
  filter(pandemia == 'Pre-pandemia')

pand <- cr %>%
  filter(pandemia == 'Pandemia')

post <- cr %>%
  filter(pandemia == 'Post-pandemia')

wilcox.test(x = pre$sp,
            y = post$sp,
            mu = 0,
            paired = F,
            var.equal = F,
            conf.int = T,
            conf.level = 0.95,
            alternative = "great")
```

```{r}
# Prepatativos ACS (requiere gplots)

base$spCat <- base$sp
cr$spCat <- cr$sp

base$spCat[base$sp < 3] <- 'Bajo'
base$spCat[base$sp > 5] <- 'Alto'
base$spCat[base$spCat !='Bajo' & base$spCat != 'Alto'] <- 'Regular'

cr$spCat[cr$sp < 3] <- 'Bajo'
cr$spCat[cr$sp > 5] <- 'Alto'
cr$spCat[cr$spCat !='Bajo' & cr$spCat != 'Alto'] <- 'Regular'

tabla11 <- table(cr$genero, cr$spCat)
tabla1 <- table(base$universidad, base$spCat)

datos.acs.cr <- as.matrix(tabla11)
datos.acs <- as.matrix(tabla1)

tabla22 <- prop.table(tabla11,margin=1)

summary(datos.acs)
```
```{r}
# Prueba de independencia Chi-cuadrado

# H0: Las variables son independientes.
# H1: Las variables no son independientes.

chisq.test(datos.acs.cr)
#No se rechaza H0 :(

chisq.test(datos.acs)

# Se rechaza H0 :)
```
```{r}
# Prepatativos ACS (requiere gplots)

tabla.beca.cr <- table(cr$beca, cr$spCat)

datos.acs.cr.beca <- as.matrix(tabla.beca.cr)


tabla2.beca.cr <- prop.table(tabla.beca.cr,margin=1)

```


```{r}
# Prueba de independencia Chi-cuadrado

# H0: Las variables son independientes.
# H1: Las variables no son independientes.

chisq.test(tabla.beca.cr)
#No se rechaza H0 :(

```
```{r}
# Prepatativos ACS (requiere gplots)

tabla.zona.cr <- table(cr$zona, cr$spCat)

datos.acs.cr.zona <- as.matrix(tabla.zona.cr)


tabla2.zona.cr <- prop.table(tabla.zona.cr,margin=1)

```


```{r}
# Prueba de independencia Chi-cuadrado

# H0: Las variables son independientes.
# H1: Las variables no son independientes.

chisq.test(tabla.zona.cr)
#No se rechaza H0 :(

```
```{r}
# Prepatativos ACS (requiere gplots)

tabla.ingreso.cr <- table(cr$ingreso, cr$spCat)

datos.acs.cr.ingreso <- as.matrix(tabla.ingreso.cr)


tabla2.ingreso.cr <- prop.table(tabla.ingreso.cr,margin=1)

```


```{r}
# Prueba de independencia Chi-cuadrado

# H0: Las variables son independientes.
# H1: Las variables no son independientes.

chisq.test(tabla.ingreso.cr)
#No se rechaza H0 :(

```
```{r}
# Prepatativos ACS (requiere gplots)

tabla.area.cr <- table(cr$area, cr$spCat)

datos.acs.cr.area <- as.matrix(tabla.area.cr)


tabla2.area.cr <- prop.table(tabla.area.cr,margin=1)

```


```{r}
# Prueba de independencia Chi-cuadrado

# H0: Las variables son independientes.
# H1: Las variables no son independientes.

chisq.test(tabla.area.cr)
#Se rechaza H0 :)

```
```{r}
# Análisis de Correspondencia Simple (requiere gmodels y FactoMineR)
CrossTable(datos.acs.cr.area, prop.t = F, prop.r = F, prop.c = F, prop.chisq = F)

res.ca.cr.area <- CA(datos.acs.cr.area, ncp = 2, graph = T)

fviz_ca_biplot(res.ca.cr.area, repel = T, title = "Análisis de Correspondencia Simple")
```

```{r}
# Análisis de Correspondencia Simple (requiere gmodels y FactoMineR)
CrossTable(datos.acs, prop.t = F, prop.r = F, prop.c = F, prop.chisq = F)

res.ca <- CA(datos.acs, ncp = 2, graph = T)

fviz_ca_biplot(res.ca, repel = T, title = "Análisis de Correspondencia Simple")
```
```{r}
# Análisis simple -  Género y sentido de pertenencia

#Primero se eliminan los 6 datos de otro

basesinotro <- base[-c(2,3,452,484,597,600),]

tabla2 <- table(basesinotro$genero,basesinotro$spCat) 

datos.acs2 <- as.matrix(tabla2)

# Prueba de independencia Chi-cuadrado

# H0: Las variables son independientes.
# H1: Las variables no son independientes.

chisq.test(datos.acs2)

# No se rechaza H0 :(

cs <- CA(datos.acs2, ncp=2, graph = T)
fviz_ca_biplot(cs, repel = T, title = "Análisis de Correspondencia Simple")

```
```{r}
# Análisis simple -  zona y sentido de pertenencia

tabla3 <- table(base$zona,base$spCat)

datos.acs3 <- as.matrix(tabla3)

# Prueba de independencia Chi-cuadrado

# H0: Las variables son independientes.
# H1: Las variables no son independientes.

chisq.test(datos.acs3)

# No se rechaza H0 :(

```

```{r}
# Análisis simple -  beca y sentido de pertenencia

tabla4 <- table(base$beca,base$spCat)

datos.acs4 <- as.matrix(tabla4)

# Prueba de independencia Chi-cuadrado

# H0: Las variables son independientes.
# H1: Las variables no son independientes.

chisq.test(datos.acs4)

# Se rechaza H0 :)

rcs <- CA(datos.acs4, ncp = 2, graph = T)
fviz_ca_biplot(rcs, repel = T, title = "Análisis de Correspondencia Simple")
```




```{r}
baseacm <- base %>%
  select(c("universidad", "STEM", "spCat"))

tablam1 <- table(baseacm)

datos.acm1 <- as.matrix.data.frame(tablam1)

# Prueba de independencia Chi-cuadrado

# H0: Las variables son independientes.
# H1: Las variables no son independientes.

chisq.test(datos.acm1)

# Se rechaza H0 :)

mult1 <- MCA(baseacm, ncp=5, graph = T)

head(baseacm)

#Diagrama de variables

fviz_mca_var(mult1, choice = c("var.cat", "mca.cor", "var", "quanti.sup"),
  axes = c(1, 2), geom = c("point", "text"),
  repel = FALSE, col.var = "red", alpha.var = 1, shape.var = 17,
  col.quanti.sup = "blue", col.quali.sup = "darkgreen",
  map = "symmetric")


chisq.test(baseacm)
```



```{r}
#Análisis género y stem
baseacm2 <- base %>%
  select(c("genero", "STEM", "spCat"))

tablam2 <- table(baseacm2)

datos.acm2 <- as.matrix(tablam2)

# Prueba de independencia Chi-cuadrado

# H0: Las variables son independientes.
# H1: Las variables no son independientes.

chisq.test(datos.acm2)

# No se rechaza H0 :(

```

```{r}
# Análisis de pandemia y SP (simple)

# Preparativos

tabla2 <- table(base$pandemia, base$spCat)

datos.acs2 <- as.matrix(tabla2)

# Prueba de independencia Chi-cuadrado

# H0: Las variables son independientes.
# H1: Las variables no son independientes.

chisq.test(datos.acs2)

# No se rechaza H0 :(

```

```{r}
baseacm3 <- basesinotro %>%
  select(c("universidad", "STEM", "spCat", "beca", "ingreso", "genero", "zona"))

tablam3 <- table(baseacm3)

datos.acm3 <- as.matrix(tablam3)

# Prueba de independencia Chi-cuadrado

# H0: Las variables son independientes.
# H1: Las variables no son independientes.

chisq.test(datos.acm3)

# Se rechaza H0 :)

mult3 <- MCA(baseacm3, ncp=5, graph = T)

head(baseacm)

#Diagrama de variables

fviz_mca_var(mult1, choice = c("var.cat", "mca.cor", "var", "quanti.sup"),
  axes = c(1, 2), geom = c("point", "text"),
  repel = FALSE, col.var = "red", alpha.var = 1, shape.var = 17,
  col.quanti.sup = "blue", col.quali.sup = "darkgreen",
  map = "symmetric")


chisq.test(baseacm)
```

```{r}
baseacm <- base %>%
  select(c("universidad", "STEM", "spCat"))

tablam1 <- table(baseacm)

datos.acm1 <- as.matrix.data.frame(tablam1)

# Prueba de independencia Chi-cuadrado

# H0: Las variables son independientes.
# H1: Las variables no son independientes.

chisq.test(datos.acm1)

# Se rechaza H0 :)

mult1 <- MCA(baseacm, ncp=5, graph = T)

head(baseacm)

#Diagrama de variables

fviz_mca_var(mult1, choice = c("var.cat", "mca.cor", "var", "quanti.sup"),
  axes = c(1, 2), geom = c("point", "text"),
  repel = FALSE, col.var = "red", alpha.var = 1, shape.var = 17,
  col.quanti.sup = "blue", col.quali.sup = "darkgreen",
  map = "symmetric")


chisq.test(baseacm)
```



```{r}
#Análisis género y stem
baseacm2 <- base %>%
  select(c("genero", "STEM", "spCat"))

tablam2 <- table(baseacm2)

datos.acm2 <- as.matrix(tabla2)

# Prueba de independencia Chi-cuadrado

# H0: Las variables son independientes.
# H1: Las variables no son independientes.

chisq.test(datos.acm2)

# No se rechaza H0 :(

```

```{r}
# Análisis de pandemia y SP (simple)

# Preparativos

tabla2 <- table(base$pandemia, base$spCat)

datos.acs2 <- as.matrix(tabla2)

# Prueba de independencia Chi-cuadrado

# H0: Las variables son independientes.
# H1: Las variables no son independientes.

chisq.test(datos.acs2)

# No se rechaza H0 :(

```

```{r}
baseacmcr6 <- cr %>%
  select(c("STEM", "spCat", "beca", "ingreso", "genero", "zona"))

tabla.m.cr6 <- table(baseacmcr6)

datos.acm.cr6 <- as.matrix(tabla.m.cr6)

# Prueba de independencia Chi-cuadrado

# H0: Las variables son independientes.
# H1: Las variables no son independientes.

chisq.test(datos.acm.cr6)

# Se rechaza H0 :)

mult.cr6 <- MCA(as.matrix(baseacmcr6), ncp=5, graph = T)

head(baseacm)

#Diagrama de variables

fviz_mca_var(mult.cr6, choice = c("var.cat", "mca.cor", "var", "quanti.sup"),
  axes = c(1, 2), geom = c("point", "text"),
  repel = FALSE, col.var = "red", alpha.var = 1, shape.var = 17,
  col.quanti.sup = "blue", col.quali.sup = "darkgreen",
  map = "symmetric")


chisq.test(baseacm)
```
```{r}
baseacmcr2 <- cr %>%
  select(c("STEM", "spCat", "genero"))

tabla.m.cr2 <- table(baseacmcr2)

datos.acm.cr2 <- as.matrix(tabla.m.cr2)

# Prueba de independencia Chi-cuadrado

# H0: Las variables son independientes.
# H1: Las variables no son independientes.

chisq.test(datos.acm.cr2)

# Se rechaza H0 :)

mult.cr2 <- MCA(as.matrix(baseacmcr2), ncp=5, graph = T)

head(baseacm)

#Diagrama de variables

fviz_mca_var(mult.cr2, choice = c("var.cat", "mca.cor", "var", "quanti.sup"),
  axes = c(1, 2), geom = c("point", "text"),
  repel = FALSE, col.var = "red", alpha.var = 1, shape.var = 17,
  col.quanti.sup = "blue", col.quali.sup = "darkgreen",
  map = "symmetric")


chisq.test(baseacm)
```

```{r}
library(caTools)

set.seed(123)
#dividir
split = sample.split(cr$genero, SplitRatio=0.5) ## dividir a la mitad el conjunto de datos


AFE = subset(cr, split==TRUE)# la mitad para el exploratorio


AFC = subset(cr, split==FALSE)# La otra mitad para el confirmatorio

## Datos en cada set
nrow(AFC)


nrow(AFE)
```


```{r}
## Análisis factorial exploratorio
Items <- data.frame(AFE$AF1 , AFE$AF2 , AFE$AF3 , AFE$AF4 , AFE$AF5 , AFE$AF6 , AFE$AF7 , AFE$AF8,AFE$S1 , AFE$S2, AFE$S3 ,AFE$S4, AFE$AC1 , AFE$AC2,AFE$AC3 , AFE$AC4, AFE$F1 , AFE$F2 , AFE$F3 , AFE$F4)  
    

library(polycor)
mat_cor <- hetcor(Items)$correlations #matriz de correlación policorica
```


```{r}
# Test de Bartlett y KMO
library(psych)
p_esf<-cortest.bartlett(mat_cor)
p_esf
KMO(mat_cor)
```

```{r}
# Análisis Paralelo 
fa.parallel(mat_cor,n.obs =dim(AFE)[1] ,fa="fa",fm="minres")
```

```{r}
# Análisis Factorial exploratorio
modelo_oblimin<-fa(mat_cor,nfactors = 5,rotate = "oblimin",fm="minres")

# Tabla de cargas factoriales
print(modelo_oblimin$loadings,cut=0.0) 

fa.diagram(modelo_oblimin,main = "Análisis Factorial")
modelo_oblimin$R2.scores
```

```{r}
#Estadísticos de bondad de ajuste para el Análisis Factorial
AFEBA<-fa(Items,nfactors = 5,rotate = "oblimin",fm="minres")

AFEBA$RMSEA
AFEBA$TLI
AFEBA$rms
AFEBA$R2
AFEBA$Vaccounted
```


```{r}
#Confiabilidad Exploratorio preliminares
afectivaAFE <- AFE$AF1 + AFE$AF2 + AFE$AF3 + AFE$AF4 + AFE$AF5 + AFE$AF6 + AFE$AF7 + AFE$AF8
socialAFE <- AFE$S1 + AFE$S2 + AFE$S3 + AFE$S4
academicaAFE <- AFE$AC1 + AFE$AC2 + AFE$AC3 + AFE$AC4
fisicaAFE <- AFE$F1 + AFE$F2 + AFE$F3 + AFE$F4
spAFE <- afectivaAFE + socialAFE + academicaAFE + fisicaAFE

AFAFE <- AFE[,c(8:15)]
SAFE<- AFE[,c(16:19)]
ACAFE<- AFE[,c(20:23)]
FIAFE <- AFE[,c(24:27)] 

afectivaAFE <- rescale(afectivaAFE, to = c(1,7))
socialAFE <- rescale(socialAFE, to = c(1,7))
academicaAFE <- rescale(academicaAFE, to = c(1,7))
fisicaAFE <- rescale(fisicaAFE, to = c(1,7))
spAFE <- rescale(spAFE, to = c(1,7))
```

```{r}
#Omegas y alfas
psych::omega(AFAFE, nfactors=2)
psych::alpha(AFAFE)

psych::omega(SAFE, nfactors=1)
psych::alpha(SAFE)

psych::omega(ACAFE, nfactors=1)
psych::alpha(ACAFE)

psych::omega(FIAFE, nfactors=1)
psych::alpha(FIAFE)

```

```{r}
library(modeest)

#Resumen por dimensión
summary(afectivaAFE)
sd(afectivaAFE)
mfv(afectivaAFE)

summary(socialAFE)
sd(socialAFE)
mfv(socialAFE)

summary(academicaAFE)
sd(academicaAFE)
mfv(academicaAFE)

summary(fisicaAFE)
sd(fisicaAFE)
mfv(fisicaAFE)
```

```{r}
# Confirmatorio
cfaCR_conf <- lavaan::cfa(model=modelo1, data=AFC, orthogonal = F, std.lv=T, std.ov=T,test = "Satorra.Bentler",estimator="WLSMV",ordered=T)
lavaan::fitmeasures(cfaCR_conf, fit.measures="all")
```

```{r}
#Confiabilidad Confirmatorio preliminares
afectivaAFC <- AFC$AF1 + AFC$AF2 + AFC$AF3 + AFC$AF4 + AFC$AF5 + AFC$AF6 + AFC$AF7 + AFC$AF8
socialAFC <- AFC$S1 + AFC$S2 + AFC$S3 + AFC$S4
academicaAFC <- AFC$AC1 + AFC$AC2 + AFC$AC3 + AFC$AC4
fisicaAFC <- AFC$F1 + AFC$F2 + AFC$F3 + AFC$F4
spAFC <- afectivaAFC + socialAFC + academicaAFC + fisicaAFC

AFAFC <- AFC[,c(8:15)]
SAFC<- AFC[,c(16:19)]
ACAFC<- AFC[,c(20:23)]
FIAFC <- AFC[,c(24:27)] 

afectivaAFC <- rescale(afectivaAFC, to = c(1,7))
socialAFC <- rescale(socialAFC, to = c(1,7))
academicaAFC <- rescale(academicaAFC, to = c(1,7))
fisicaAFC <- rescale(fisicaAFC, to = c(1,7))
spAFC <- rescale(spAFC, to = c(1,7))
```

```{r}
#Omegas y alfas
psych::omega(AFAFC, nfactors=2)
psych::alpha(AFAFC)

psych::omega(SAFC, nfactors=1)
psych::alpha(SAFC)

psych::omega(ACAFC, nfactors=1)
psych::alpha(ACAFC)

psych::omega(FIAFC, nfactors=1)
psych::alpha(FIAFC)
```

```{r}
library(modeest)

#Resumen por dimensión
summary(afectivaAFC)
sd(afectivaAFC)
mfv(afectivaAFC)

summary(socialAFC)
sd(socialAFC)
mfv(socialAFC)

summary(academicaAFC)
sd(academicaAFC)
mfv(academicaAFC)

summary(fisicaAFC)
sd(fisicaAFC)
mfv(fisicaAFC)
```

